export enum ELinks{
    LINK_HOMEPAGE = '/',
    LINK_ABOUTPAGE = '/about',
    LINK_BLOGPAGE = '/blog',
    LINK_ITEM_BLOGPAGE = '/blog/:id',
    LINK_FAVORITEPAGE = '/favorite',
    LINK_PROFILEPAGE = '/profile',
    LINK_CARTPAGE = '/cart',
    LINK_CATALOGPAGE = '/catalog',
    LINK_ITEM_CATALOGPAGE = '/catalog/:id',
    LINK_SIGNIN = '/auth/login',
    LINK_SIGNUP = '/auth/reg',
    LINK_PRIVACYPAGE = '/privacy-police',
    LINK_TERMSPAGE = '/terms-and-conditions',
    LINK_ANOTHER = '*',
}